# Generated by Django 4.0.10 on 2024-04-27 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='target',
            fields=[
                ('targetID', models.AutoField(primary_key=True, serialize=False)),
                ('targetName', models.CharField(max_length=255)),
                ('catalogIDs', models.CharField(max_length=255)),
                ('targetType', models.CharField(choices=[('VS', 'Variable Star'), ('EX', 'Exoplanet'), ('DS', 'Deep Sky Object'), ('PL', 'Planet'), ('LU', 'Luna'), ('SU', 'Sun'), ('SA', 'Satellite'), ('OT', 'Other')], max_length=2)),
                ('objID', models.CharField(max_length=200)),
                ('objName', models.CharField(max_length=200)),
                ('objRA2000', models.CharField(max_length=200)),
                ('objDec2000', models.CharField(max_length=200)),
                ('objConst', models.CharField(max_length=200)),
                ('objMag', models.CharField(max_length=200)),
                ('objSize', models.CharField(max_length=200)),
                ('objType', models.CharField(max_length=200)),
                ('objClass', models.CharField(max_length=200)),
                ('objCatalogs', models.CharField(max_length=200)),
            ],
        ),
    ]
