# Generated by Django 5.1.4 on 2024-12-24 03:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='simbadType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('targetId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('targetName', models.CharField(max_length=255)),
                ('targetClass', models.CharField(choices=[('VS', 'Variable Star'), ('EX', 'Exoplanet'), ('DS', 'Deep Sky Object'), ('PL', 'Planet'), ('LU', 'Luna'), ('SU', 'Sun'), ('SA', 'Satellite'), ('OT', 'Other')], default='DS', max_length=2)),
                ('targetType', models.CharField(max_length=255)),
                ('targetRA2000', models.CharField(max_length=255)),
                ('targetDec2000', models.CharField(max_length=255)),
                ('targetConst', models.CharField(max_length=200)),
                ('targetMag', models.CharField(max_length=200)),
                ('targetDefaultThumbnail', models.ImageField(upload_to='thumbnails/')),
            ],
        ),
    ]
