# Generated by Django 4.0.10 on 2024-03-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TargetModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('target', models.CharField(max_length=255)),
                ('catalogID', models.CharField(max_length=255)),
            ],
        ),
    ]
