# Generated by Django 4.0.10 on 2024-05-29 16:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule',
            fields=[
                ('scheduleId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=255)),
                ('scheduleDate', models.DateField()),
                ('startUpUnparkDome', models.BooleanField(default=False)),
                ('startUpUnparkMount', models.BooleanField(default=False)),
                ('startUpUnCap', models.BooleanField(default=False)),
                ('onAbortJobMgmt', models.CharField(choices=[('None', 'None'), ('Queue', 'Queue'), ('Immediate', 'Immediate')], default='None', max_length=10)),
                ('rescheduleErrorsSecs', models.IntegerField(default=0)),
                ('jobConstraintsAlt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsMoon', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsWeather', models.BooleanField(default=False)),
                ('jobConstraintTwilight', models.BooleanField(default=False)),
                ('jobConstraintArtHor', models.BooleanField(default=False)),
                ('jobCompleteCondSeq', models.BooleanField(default=False)),
                ('jobCompleteCondRepeatNo', models.IntegerField(default=0)),
                ('jobCompleteCondRepeatAll', models.BooleanField(default=False)),
                ('jobCompleteCondRepeatUntil', models.DateField()),
                ('ShutDownParkDome', models.BooleanField(default=False)),
                ('ShutDownParkMount', models.BooleanField(default=False)),
                ('ShutDownCap', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='target',
            name='catalogIDs',
        ),
        migrations.AddField(
            model_name='target',
            name='observeOnce',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='target',
            name='targetInactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='target',
            name='targetPA',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.CreateModel(
            name='scheduleDetail',
            fields=[
                ('scheduleDetailId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduledDateTime', models.DateTimeField()),
                ('targetPriority', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('requiredStartTime', models.DateTimeField()),
                ('requiredStartCulOffset', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jobConstraintsAlt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsMoon', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsWeather', models.BooleanField(default=False)),
                ('jobConstraintTwilight', models.BooleanField(default=False)),
                ('jobConstraintArtHor', models.BooleanField(default=False)),
                ('jobStepTrack', models.BooleanField(default=True)),
                ('jobStepFocus', models.BooleanField(default=True)),
                ('jobStepAlign', models.BooleanField(default=True)),
                ('jobStepGuide', models.BooleanField(default=True)),
                ('scheduleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.schedule')),
                ('targetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target')),
            ],
        ),
    ]
