# Generated by Django 5.1.5 on 2025-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimbadType',
        ),
        migrations.AlterField(
            model_name='target',
            name='targetClass',
            field=models.CharField(default='DS', max_length=255),
        ),
    ]
