# Generated by Django 4.0.10 on 2024-03-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='catalogID',
            new_name='catalogIDs',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='target',
            new_name='targetName',
        ),
    ]
