# Generated by Django 4.0.10 on 2024-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='userID',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
