# Generated by Django 4.0.10 on 2024-05-29 19:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_schedule_remove_target_catalogids_target_observeonce_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleFile',
            fields=[
                ('scheduleFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduleFilePath', models.FileField(max_length=4096, upload_to='schedule/')),
                ('scheduleFileData', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='sequenceFile',
            fields=[
                ('sequenceFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequenceFilePath', models.FileField(max_length=4096, upload_to='sequence/')),
                ('sequenceFileData', models.CharField(max_length=4096)),
            ],
        ),
        migrations.RenameModel(
            old_name='schedule',
            new_name='scheduleMaster',
        ),
    ]
