# Generated by Django 5.1.5 on 2025-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_delete_simbadtype_alter_target_targetclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='targetRise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='targetSet',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='target',
            name='targetTransit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
