# Generated by Django 4.0.10 on 2024-03-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_rename_catalogid_target_catalogids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='targetType',
            field=models.CharField(choices=[('VS', 'Variable Star'), ('EX', 'Exoplanet'), ('DS', 'Deep Sky Object'), ('PL', 'Planet'), ('LU', 'Luna'), ('SU', 'Sun'), ('SA', 'Satellite')], default='DS', max_length=2),
            preserve_default=False,
        ),
    ]
