# Generated by Django 4.0.10 on 2024-05-21 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_target_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='targetID',
            new_name='targetId',
        ),
    ]
