# Generated by Django 4.0.10 on 2024-05-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_rename_targetid_target_targetid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='userID',
            new_name='userId',
        ),
    ]
