# Generated by Django 4.0.10 on 2024-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_schedulefile_sequencefile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulefile',
            name='scheduleFilePath',
        ),
        migrations.RemoveField(
            model_name='sequencefile',
            name='sequenceFilePath',
        ),
        migrations.AddField(
            model_name='schedulefile',
            name='scheduleFileName',
            field=models.FileField(default='', max_length=4096, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sequencefile',
            name='sequenceFileName',
            field=models.FileField(default='', max_length=4096, upload_to=''),
            preserve_default=False,
        ),
    ]
