# Generated by Django 5.1.4 on 2024-12-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_rename_category_simbadtype_targetclass_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCVS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constellation', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('ra', models.FloatField()),
                ('dec', models.FloatField()),
                ('variable_type', models.CharField(max_length=255)),
                ('max_magnitude', models.CharField(max_length=255)),
                ('min_magnitude', models.CharField(max_length=255)),
                ('epoch', models.CharField(max_length=255)),
                ('period', models.FloatField()),
            ],
        ),
    ]
