# Generated by Django 4.0.10 on 2024-06-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0004_remove_schedulefile_schedulefilepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefile',
            name='scheduleFileName',
            field=models.FileField(max_length=4096, upload_to='schedule'),
        ),
        migrations.AlterField(
            model_name='sequencefile',
            name='sequenceFileName',
            field=models.FileField(max_length=4096, upload_to='sequence'),
        ),
    ]
