# Generated by Django 5.1.4 on 2024-12-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0005_gcvs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcvs',
            name='epoch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gcvs',
            name='period',
            field=models.FloatField(null=True),
        ),
    ]
