# Generated by Django 4.0.10 on 2024-06-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_observer_middlename'),
        ('targets', '0005_alter_schedulefile_schedulefilename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='Target',
            name='imager',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Target',
            name='observatory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='Target',
            name='telescope',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
            preserve_default=False,
        ),
    ]
