# Generated by Django 5.1.4 on 2024-12-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0006_alter_gcvs_epoch_alter_gcvs_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcvs',
            name='max_magnitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gcvs',
            name='min_magnitude',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gcvs',
            name='variable_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
