# Generated by Django 5.1.4 on 2024-12-31 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0007_alter_gcvs_max_magnitude_alter_gcvs_min_magnitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcvs',
            name='dec',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='gcvs',
            name='ra',
            field=models.FloatField(null=True),
        ),
    ]
