# Generated by Django 4.0.10 on 2024-06-24 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_observer_middlename'),
        ('targets', '0007_alter_target_imager_alter_target_observatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Target',
            name='imager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
        ),
        migrations.AlterField(
            model_name='Target',
            name='observatory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
        ),
        migrations.AlterField(
            model_name='Target',
            name='telescope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
        ),
    ]
