# Generated by Django 4.0.10 on 2024-06-25 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_remove_observer_observatory_and_more'),
        ('targets', '0008_alter_target_imager_alter_target_observatory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='imager',
            new_name='imagerId',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='observatory',
            new_name='observatoryId',
        ),
        migrations.RenameField(
            model_name='target',
            old_name='telescope',
            new_name='telescopeId',
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='imagerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='observatoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='scheduleDays',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='telescopeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
        ),
    ]
