# Generated by Django 5.1.4 on 2024-12-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_remove_gcvs_id_remove_nasaexplanetarchive_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcvs',
            name='targetClass',
            field=models.CharField(default='VS', max_length=255),
        ),
        migrations.AddField(
            model_name='nasaexplanetarchive',
            name='targetClass',
            field=models.CharField(default='EX', max_length=255),
        ),
    ]
