# Generated by Django 4.0.10 on 2024-06-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0009_rename_imager_target_imagerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemaster',
            name='ShutDownCap',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='ShutDownParkDome',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='ShutDownParkMount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatAll',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatUntil',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobCompleteCondSeq',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobConstraintArtHor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobConstraintTwilight',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobConstraintsAlt',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobConstraintsMoon',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='jobConstraintsWeather',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='onAbortJobMgmt',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Queue', 'Queue'), ('Immediate', 'Immediate')], default='None', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='rescheduleErrorsSecs',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='scheduleDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='scheduleDays',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='startUpUnCap',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='startUpUnparkDome',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='startUpUnparkMount',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='userId',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
