# Generated by Django 5.1.4 on 2024-12-31 22:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_gcvs_targetclass_nasaexplanetarchive_targetclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exoplanet',
            fields=[
                ('targetId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('targetClass', models.CharField(default='EX', max_length=255)),
                ('targetName', models.CharField(max_length=255)),
                ('targetOrbPer', models.FloatField()),
                ('targetOrbPerErr1', models.FloatField()),
                ('targetOrbPerErr2', models.FloatField()),
                ('targetOrbSMAxis', models.FloatField()),
                ('targetOrbIncl', models.FloatField()),
                ('targetRAStr', models.FloatField()),
                ('targetDecStr', models.FloatField()),
                ('targetRA2000', models.FloatField()),
                ('targetDec2000', models.FloatField()),
                ('targetStelRadius', models.FloatField()),
                ('targetPlRadius', models.FloatField()),
                ('targetTrDepth', models.FloatField()),
                ('targetTrDur', models.FloatField()),
                ('targetTrDurErr1', models.FloatField()),
                ('targetTrDurErr2', models.FloatField()),
                ('targetTrMid', models.FloatField()),
                ('targetTrMidErr1', models.FloatField()),
                ('targetTrMidErr2', models.FloatField()),
                ('targetImpPar', models.FloatField()),
                ('targetRatDor', models.FloatField()),
                ('targetRarRor', models.FloatField()),
                ('targetVMag', models.FloatField()),
                ('targetGaiaMag', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='NasaExPlanetArchive',
        ),
        migrations.AlterField(
            model_name='gcvs',
            name='constellation',
            field=models.CharField(choices=[('All', 'All'), ('AND', 'Andromeda'), ('ANT', 'Antlia'), ('APS', 'Apus'), ('AQR', 'Aquarius'), ('AQL', 'Aquila'), ('ARA', 'Ara'), ('ARI', 'Aries'), ('AUR', 'Auriga'), ('BOO', 'Boötes'), ('CAE', 'Caelum'), ('CAM', 'Camelopardalis'), ('CNC', 'Cancer'), ('CVN', 'Canes Venatici'), ('CMA', 'Canis Major'), ('CMI', 'Canis Minor'), ('CAP', 'Capricornus'), ('CAR', 'Carina'), ('CAS', 'Cassiopeia'), ('CEN', 'Centaurus'), ('CEP', 'Cepheus'), ('CET', 'Cetus'), ('CHA', 'Chamaeleon'), ('CIR', 'Circinus'), ('COL', 'Columba'), ('COM', 'Coma Berenices'), ('CRA', 'Corona Australis'), ('CRB', 'Corona Borealis'), ('CRV', 'Corvus'), ('CRT', 'Crater'), ('CRU', 'Crux'), ('CYG', 'Cygnus'), ('DEL', 'Delphinus'), ('DOR', 'Dorado'), ('DRA', 'Draco'), ('EQU', 'Equuleus'), ('ERI', 'Eridanus'), ('FOR', 'Fornax'), ('GEM', 'Gemini'), ('GRU', 'Grus'), ('HER', 'Hercules'), ('HOR', 'Horologium'), ('HYA', 'Hydra'), ('HYI', 'Hydrus'), ('IND', 'Indus'), ('LAC', 'Lacerta'), ('LEO', 'Leo'), ('LMI', 'Leo Minor'), ('LEP', 'Lepus'), ('LIB', 'Libra'), ('LUP', 'Lupus'), ('LYN', 'Lynx'), ('LYR', 'Lyra'), ('MEN', 'Mensa'), ('MIC', 'Microscopium'), ('MON', 'Monoceros'), ('MUS', 'Musca'), ('NOR', 'Norma'), ('OCT', 'Octans'), ('OPH', 'Ophiuchus'), ('ORI', 'Orion'), ('PAV', 'Pavo'), ('PEG', 'Pegasus'), ('PER', 'Perseus'), ('PHE', 'Phoenix'), ('PIC', 'Pictor'), ('PSC', 'Pisces'), ('PSA', 'Piscis Austrinus'), ('PUP', 'Puppis'), ('PYX', 'Pyxis'), ('RET', 'Reticulum'), ('SGE', 'Sagitta'), ('SGR', 'Sagittarius'), ('SCO', 'Scorpius'), ('SCL', 'Sculptor'), ('SCT', 'Scutum'), ('SER', 'Serpens'), ('SEX', 'Sextans'), ('TAU', 'Taurus'), ('TEL', 'Telescopium'), ('TRI', 'Triangulum'), ('TRA', 'Triangulum Australe'), ('TUC', 'Tucana'), ('UMA', 'Ursa Major'), ('UMI', 'Ursa Minor'), ('VEL', 'Vela'), ('VIR', 'Virgo'), ('VOL', 'Volans'), ('VUL', 'Vulpecula')], max_length=255),
        ),
    ]
