# Generated by Django 4.0.10 on 2024-06-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0010_alter_schedulemaster_shutdowncap_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemaster',
            old_name='scheduleId',
            new_name='scheduleMasterId',
        ),
    ]
