# Generated by Django 5.1.1 on 2024-10-03 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0013_importtarget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Target',
            name='imagerId',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='observatoryId',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='observeOnce',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='targetInactive',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='targetPA',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='telescopeId',
        ),
        migrations.RemoveField(
            model_name='Target',
            name='userId',
        ),
    ]
