# Generated by Django 5.1.2 on 2024-10-10 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0014_remove_target_imagerid_remove_target_observatoryid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledetail',
            name='scheduleMasterId',
        ),
        migrations.RemoveField(
            model_name='scheduledetail',
            name='targetId',
        ),
        migrations.DeleteModel(
            name='scheduleFile',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='imagerId',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='observatoryId',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='telescopeId',
        ),
        migrations.DeleteModel(
            name='sequenceFile',
        ),
        migrations.DeleteModel(
            name='scheduleDetail',
        ),
        migrations.DeleteModel(
            name='scheduleMaster',
        ),
    ]
