# Generated by Django 5.1.4 on 2024-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0016_delete_importtarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='targetDefaultThumbnail',
            field=models.CharField(default='static/images/thumbnails/default.jpg', max_length=255),
        ),
    ]
