# Generated by Django 5.1.4 on 2024-12-10 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0018_alter_target_targetdefaultthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='targetDec2000',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetRA2000',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
