# Generated by Django 5.1.4 on 2024-12-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0019_alter_target_targetdec2000_alter_target_targetra2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='targetDec2000',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetRA2000',
            field=models.FloatField(default=0.0),
        ),
    ]
