# Generated by Django 5.1.4 on 2024-12-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0020_alter_target_targetdec2000_alter_target_targetra2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='targetClass',
            field=models.CharField(choices=[('VS', 'Variable Star'), ('EX', 'Exoplanet'), ('DS', 'Deep Sky Object'), ('PL', 'Planet'), ('LU', 'Luna'), ('SU', 'Sun'), ('SA', 'Satellite'), ('OT', 'Other')], default='DS', max_length=2),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetDec2000',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='target',
            name='targetRA2000',
            field=models.CharField(max_length=255),
        ),
    ]
