# Generated by Django 5.1.4 on 2024-12-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0021_alter_target_targetclass_alter_target_targetdec2000_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='target',
            name='targetDefaultThumbnail',
            field=models.ImageField(default='', upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
