# Generated by Django 5.1.5 on 2025-01-18 17:16

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0001_initial'),
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitsFile',
            fields=[
                ('fitsFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitsFileName', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileDate', models.DateTimeField(default=datetime.datetime.now)),
                ('fitsFileCalibrated', models.BooleanField(default=False)),
                ('fitsFileType', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileStacked', models.BooleanField(default=False)),
                ('fitsFileObject', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileExpTime', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileXBinning', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileYBinning', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileCCDTemp', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileTelescop', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileInstrument', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileGain', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileOffset', models.CharField(blank=True, default='None', max_length=255, null=True)),
                ('fitsFileSequence', models.UUIDField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='fitsSequence',
            fields=[
                ('fitsSequenceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitsSequenceObjectName', models.CharField(blank=True, max_length=255, null=True)),
                ('fitsSequenceDate', models.DateTimeField(default=datetime.datetime.now)),
                ('fitsMasterBias', models.CharField(blank=True, max_length=255, null=True)),
                ('fitsMasterDark', models.CharField(blank=True, max_length=255, null=True)),
                ('fitsMasterFlat', models.UUIDField(blank=True, null=True)),
                ('fitsSequenceThumbnailPath', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observationDate', models.DateField(blank=True, null=True)),
                ('targetClass', models.CharField(blank=True, max_length=255, null=True)),
                ('userId', models.CharField(max_length=255)),
                ('targetPA', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('targetInactive', models.BooleanField(default=False)),
                ('observeOnce', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=255, null=True)),
                ('scheduledDateTime', models.DateTimeField(blank=True, null=True)),
                ('actualDateTime', models.DateTimeField(blank=True, null=True)),
                ('actualDuration', models.IntegerField(default=0)),
                ('fitsFileSequence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.fitssequence')),
                ('imagerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager')),
                ('observatoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
                ('targetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.target')),
                ('telescopeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope')),
            ],
        ),
        migrations.CreateModel(
            name='sequenceFile',
            fields=[
                ('sequenceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequenceFileName', models.CharField(max_length=255)),
                ('sequenceData', models.CharField(max_length=4096)),
                ('sequenceDuration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ObservationDS',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='ObservationEX',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='ObservationVS',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='scheduleDetail',
            fields=[
                ('scheduleDetailId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduledDateTime', models.DateTimeField()),
                ('targetPriority', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('requiredStartTime', models.DateTimeField()),
                ('requiredStartCulOffset', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jobConstraintsAlt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsMoon', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsWeather', models.BooleanField(default=False)),
                ('jobConstraintTwilight', models.BooleanField(default=False)),
                ('jobConstraintArtHor', models.BooleanField(default=False)),
                ('jobStepTrack', models.BooleanField(default=True)),
                ('jobStepFocus', models.BooleanField(default=True)),
                ('jobStepAlign', models.BooleanField(default=True)),
                ('jobStepGuide', models.BooleanField(default=True)),
                ('targetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.target')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleMaster',
            fields=[
                ('scheduleMasterId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduleDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('scheduleDays', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)])),
                ('imagerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager')),
                ('observations', models.ManyToManyField(to='observations.scheduledetail')),
                ('observatoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
                ('telescopeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope')),
                ('sequenceFileId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.sequencefile')),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='scheduleMasterId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.schedulemaster'),
        ),
        migrations.AddField(
            model_name='observation',
            name='sequenceFileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.sequencefile'),
        ),
    ]
