# Generated by Django 5.1.1 on 2024-10-03 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('setup', '0013_remove_observer_observatory_and_more'),
        ('targets', '0014_remove_target_imagerid_remove_target_observatoryid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='observation',
            fields=[
                ('observationId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('observationDate', models.DateField(blank=True, null=True)),
                ('userId', models.CharField(max_length=255)),
                ('targetPA', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('targetInactive', models.BooleanField(default=False)),
                ('observeOnce', models.BooleanField(default=True)),
                ('imagerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager')),
                ('observatoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
                ('targetId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
                ('telescopeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope')),
            ],
        ),
    ]
