# Generated by Django 5.1.5 on 2025-01-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='targetName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
