# Generated by Django 5.1.4 on 2024-12-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservationDS',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='ObservationEX',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
        migrations.CreateModel(
            name='ObservationVS',
            fields=[
                ('observation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='observations.observation')),
            ],
            bases=('observations.observation',),
        ),
    ]
