# Generated by Django 5.1.2 on 2024-10-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='observeOnce',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='observation',
            name='targetPA',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True),
        ),
    ]
