# Generated by Django 5.1.2 on 2024-10-10 03:30

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0002_alter_observation_observeonce_and_more'),
        ('setup', '0016_alter_imager_imagerid_and_more'),
        ('targets', '0015_remove_scheduledetail_schedulemasterid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduleFile',
            fields=[
                ('scheduleFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduleFileName', models.FileField(max_length=4096, upload_to='schedule')),
                ('scheduleFileData', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='sequenceFile',
            fields=[
                ('sequenceFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequenceFileName', models.FileField(max_length=4096, upload_to='sequence')),
                ('sequenceFileData', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='scheduleMaster',
            fields=[
                ('scheduleMasterId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('userId', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduleDate', models.DateField(blank=True, null=True)),
                ('scheduleDays', models.IntegerField(blank=True, null=True)),
                ('startUpUnparkDome', models.BooleanField(blank=True, default=False, null=True)),
                ('startUpUnparkMount', models.BooleanField(blank=True, default=False, null=True)),
                ('startUpUnCap', models.BooleanField(blank=True, default=False, null=True)),
                ('onAbortJobMgmt', models.CharField(blank=True, choices=[('None', 'None'), ('Queue', 'Queue'), ('Immediate', 'Immediate')], default='None', max_length=10, null=True)),
                ('rescheduleErrorsSecs', models.IntegerField(blank=True, default=0, null=True)),
                ('jobConstraintsAlt', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('jobConstraintsMoon', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True)),
                ('jobConstraintsWeather', models.BooleanField(blank=True, default=False, null=True)),
                ('jobConstraintTwilight', models.BooleanField(blank=True, default=False, null=True)),
                ('jobConstraintArtHor', models.BooleanField(blank=True, default=False, null=True)),
                ('jobCompleteCondSeq', models.BooleanField(blank=True, default=False, null=True)),
                ('jobCompleteCondRepeatNo', models.IntegerField(blank=True, default=0, null=True)),
                ('jobCompleteCondRepeatAll', models.BooleanField(blank=True, default=False, null=True)),
                ('jobCompleteCondRepeatUntil', models.DateField(blank=True, null=True)),
                ('ShutDownParkDome', models.BooleanField(blank=True, default=False, null=True)),
                ('ShutDownParkMount', models.BooleanField(blank=True, default=False, null=True)),
                ('ShutDownCap', models.BooleanField(blank=True, default=False, null=True)),
                ('imagerId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager')),
                ('observatoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
                ('telescopeId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope')),
            ],
        ),
        migrations.CreateModel(
            name='scheduleDetail',
            fields=[
                ('scheduleDetailId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduledDateTime', models.DateTimeField()),
                ('targetPriority', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('requiredStartTime', models.DateTimeField()),
                ('requiredStartCulOffset', models.DecimalField(decimal_places=2, max_digits=6)),
                ('jobConstraintsAlt', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsMoon', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('jobConstraintsWeather', models.BooleanField(default=False)),
                ('jobConstraintTwilight', models.BooleanField(default=False)),
                ('jobConstraintArtHor', models.BooleanField(default=False)),
                ('jobStepTrack', models.BooleanField(default=True)),
                ('jobStepFocus', models.BooleanField(default=True)),
                ('jobStepAlign', models.BooleanField(default=True)),
                ('jobStepGuide', models.BooleanField(default=True)),
                ('targetId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='targets.Target')),
                ('scheduleMasterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.schedulemaster')),
            ],
        ),
    ]
