# Generated by Django 5.1.2 on 2024-10-26 19:59

import datetime
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0003_schedulefile_sequencefile_schedulemaster_and_more'),
        ('setup', '0018_delete_currentconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitsFile',
            fields=[
                ('fitsFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitsFileName', models.CharField(max_length=255)),
                ('fitsFileDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledetail',
            name='scheduleMasterId',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='ShutDownCap',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='ShutDownParkDome',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='ShutDownParkMount',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatAll',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatNo',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobCompleteCondRepeatUntil',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobCompleteCondSeq',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobConstraintArtHor',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobConstraintTwilight',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobConstraintsAlt',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobConstraintsMoon',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='jobConstraintsWeather',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='onAbortJobMgmt',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='rescheduleErrorsSecs',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='scheduleDate',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='scheduleDays',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='startUpUnCap',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='startUpUnparkDome',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='startUpUnparkMount',
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='observations',
            field=models.ManyToManyField(to='observations.scheduledetail'),
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='schedule_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='schedule_days',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(365), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='imagerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='observatoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='telescopeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='userId',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='fitsHeader',
            fields=[
                ('fitsHeaderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitsHeaderKey', models.CharField(max_length=255)),
                ('fitsHeaderValue', models.CharField(max_length=255)),
                ('fitsFileId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observations.fitsfile')),
            ],
        ),
    ]
