# Generated by Django 5.1.5 on 2025-01-20 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0004_remove_fitssequence_fitssequencethumbnailpath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 11, 5, 28, 571777, tzinfo=datetime.timezone.utc)),
        ),
    ]
