# Generated by Django 5.1.5 on 2025-01-20 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_alter_fitsfile_fitsfiledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 12, 45, 45, 506548, tzinfo=datetime.timezone.utc)),
        ),
    ]
