# Generated by Django 5.1.2 on 2024-10-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0005_fitsfile_fitsfilecalibrated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileStacked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileType',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
