# Generated by Django 5.1.5 on 2025-01-20 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_alter_fitsfile_fitsfiledate'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitssequence',
            name='fitsSequenceImager',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fitssequence',
            name='fitsSequenceTelescope',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 20, 13, 53, 0, 515957, tzinfo=datetime.timezone.utc)),
        ),
    ]
