# Generated by Django 5.1.2 on 2024-11-06 16:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0006_fitsfile_fitsfilestacked_fitsfile_fitsfiletype'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitsSequence',
            fields=[
                ('fitsSequenceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fitsMasterBias', models.CharField(max_length=255)),
                ('fitsMasterDark', models.CharField(max_length=255)),
                ('fitsMasterFlat', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileCCDTemp',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileExpTime',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileGain',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileInstrument',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileObject',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileOffset',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileSequence',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileTelescop',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileXBinning',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fitsfile',
            name='fitsFileYBinning',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
