# Generated by Django 5.1.5 on 2025-01-25 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_fitssequence_fitssequenceimager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 25, 11, 29, 2, 937134, tzinfo=datetime.timezone.utc)),
        ),
    ]
