# Generated by Django 5.1.3 on 2024-11-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_fitssequence_fitsfile_fitsfileccdtemp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation',
            name='status',
            field=models.CharField(default='Pending', max_length=255, null=True),
        ),
    ]
