# Generated by Django 5.1.2 on 2024-11-10 22:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0007_fitssequence_fitsfile_fitsfileccdtemp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('sequenceId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequenceName', models.CharField(max_length=255)),
                ('sequenceFileName', models.CharField(max_length=255)),
                ('sequenceData', models.CharField(max_length=40965)),
                ('sequenceDescription', models.TextField()),
                ('sequenceDuration', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3600), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='sequenceId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.sequence'),
        ),
    ]
