# Generated by Django 5.1.2 on 2024-11-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_sequence_observation_sequenceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='sequenceName',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequenceData',
            field=models.CharField(max_length=4096),
        ),
    ]
