# Generated by Django 5.1.5 on 2025-02-01 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0008_alter_fitsfile_fitsfiledate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 1, 11, 32, 36, 13810, tzinfo=datetime.timezone.utc)),
        ),
    ]
