# Generated by Django 5.1.3 on 2024-11-08 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0009_fitssequence_fitsobject_delete_fitsheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileSequence',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
