# Generated by Django 5.1.2 on 2024-11-10 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_remove_sequence_sequencedescription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='scheduleFile',
        ),
        migrations.DeleteModel(
            name='sequenceFile',
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequenceDuration',
            field=models.IntegerField(default=0),
        ),
    ]
