# Generated by Django 5.2 on 2025-04-24 14:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0010_alter_fitsfile_fitsfiledate'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledetail',
            name='scheduleMasterId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='observations.schedulemaster'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 24, 9, 57, 15, 890613, tzinfo=datetime.timezone.utc)),
        ),
    ]
