# Generated by Django 5.1.3 on 2024-11-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_alter_fitsfile_fitsfileccdtemp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileSequence',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
