# Generated by Django 5.1.2 on 2024-11-10 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0011_delete_schedulefile_delete_sequencefile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='sequence',
            new_name='sequenceFile',
        ),
        migrations.RenameField(
            model_name='observation',
            old_name='sequenceId',
            new_name='sequenceFileId',
        ),
    ]
