# Generated by Django 5.1.3 on 2024-11-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_alter_fitsfile_fitsfilesequence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitssequence',
            name='fitsMasterBias',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitssequence',
            name='fitsMasterDark',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitssequence',
            name='fitsMasterFlat',
            field=models.CharField(default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitssequence',
            name='fitsObject',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
