# Generated by Django 5.1.2 on 2024-11-11 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0012_rename_sequence_sequencefile_and_more'),
        ('observations', '0015_alter_fitsfile_fitsfileccdtemp_and_more'),
    ]

    operations = [
    ]
