# Generated by Django 5.1.2 on 2024-11-11 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0016_merge_20241110_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedulemaster',
            old_name='schedule_date',
            new_name='scheduleDate',
        ),
        migrations.RenameField(
            model_name='schedulemaster',
            old_name='schedule_days',
            new_name='scheduleDays',
        ),
        migrations.RemoveField(
            model_name='schedulemaster',
            name='userId',
        ),
        migrations.AddField(
            model_name='observation',
            name='actualDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='actualDuration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='observation',
            name='fitsFileSequence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.fitssequence'),
        ),
        migrations.AddField(
            model_name='observation',
            name='scheduleMasterId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.schedulemaster'),
        ),
        migrations.AddField(
            model_name='observation',
            name='scheduledDateTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulemaster',
            name='sequenceFileId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='observations.sequencefile'),
            preserve_default=False,
        ),
    ]
