# Generated by Django 5.1.2 on 2024-11-11 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0017_rename_schedule_date_schedulemaster_scheduledate_and_more'),
        ('setup', '0019_delete_observer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulemaster',
            name='imagerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='sequenceFileId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='observations.sequencefile'),
        ),
        migrations.AlterField(
            model_name='schedulemaster',
            name='telescopeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
        ),
    ]
