# Generated by Django 5.1.3 on 2024-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0019_alter_fitssequence_fitsmasterbias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitssequence',
            name='fitsMasterFlat',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
