# Generated by Django 5.1.3 on 2024-11-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0020_alter_fitssequence_fitsmasterflat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitssequence',
            name='fitsObject',
        ),
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileSequence',
            field=models.UUIDField(blank=True, default='None', null=True),
        ),
    ]
