# Generated by Django 5.1.3 on 2024-11-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0021_remove_fitssequence_fitsobject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsfile',
            name='fitsFileSequence',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
