# Generated by Django 5.1.3 on 2024-11-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0023_fitssequence_fitssequencedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitssequence',
            name='fitsSequenceThumbnailPath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
