version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: obsy
      POSTGRES_USER: obsy
      POSTGRES_PASSWORD: obsy
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build: https://www.github.com/gordtulloch/obsy.git
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=obsy
      - DATABASE_USER=obsy
      - DATABASE_PASSWORD=obsy
      - DATABASE_HOST=db
      - DATABASE_PORT=5432

volumes:
  postgres_data: