version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: obsy
      POSTGRES_USER: obsy
      POSTGRES_PASSWORD: obsy
      POSTGRES_HOST_AUTH_METHOD: trust

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      - DATABASE_NAME=obsy
      - DATABASE_USER=obsy
      - DATABASE_PASSWORD=obsy
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DOCKER_CONTAINER=true

volumes:
  postgres_data: