# Generated by Django 4.0.10 on 2024-06-03 15:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fitsFile',
            fields=[
                ('fitsFileId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('filename', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='fitsHeader',
            fields=[
                ('fitsHeaderId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('parentUUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.fitsfile')),
            ],
        ),
    ]
