# Generated by Django 5.1.4 on 2024-12-24 03:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='imager',
            fields=[
                ('imagerId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('imagerType', models.CharField(choices=[('CMOS', 'CMOS'), ('CCD', 'CCD')], default='CMOS', max_length=4)),
                ('imagerColor', models.CharField(choices=[('RGB', 'RGB'), ('Mono', 'Mono')], default='RGB', max_length=4)),
                ('xDim', models.DecimalField(decimal_places=0, max_digits=5)),
                ('yDim', models.DecimalField(decimal_places=0, max_digits=5)),
                ('xPixelSize', models.DecimalField(decimal_places=2, max_digits=6)),
                ('yPixelSize', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='observatory',
            fields=[
                ('observatoryId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=8)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=9)),
                ('elevation', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('tz', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='telescope',
            fields=[
                ('telescopeId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('shortname', models.CharField(max_length=200)),
                ('telescopeType', models.CharField(choices=[('NE', 'Newtonian'), ('SC', 'Schmidt-Cassegrain'), ('CC', 'Classical Cassegrain'), ('RC', 'Ritchey Cretien Cassegrain'), ('MC', 'Mak-Cassegrain'), ('RE', 'Refractor'), ('OT', 'Other')], default='NE', max_length=2)),
                ('aperture', models.DecimalField(decimal_places=2, max_digits=6)),
                ('focalLength', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observatoryId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
            ],
        ),
        migrations.CreateModel(
            name='currentConfig',
            fields=[
                ('currentConfigId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.imager')),
                ('observatoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.observatory')),
                ('telescopeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.telescope')),
            ],
        ),
    ]
