# Generated by Django 4.0.10 on 2024-03-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fitsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thisUNID', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('filename', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='fitsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thisUNID', models.CharField(max_length=200)),
                ('parentUNID', models.CharField(max_length=200)),
                ('keyword', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
