# Generated by Django 4.0.10 on 2024-03-12 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_fitsfile_fitsheader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitsheader',
            name='parentUNID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.fitsfile'),
        ),
    ]
