# Generated by Django 4.0.10 on 2024-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_instrument_insttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='objectsCatalog',
            fields=[
                ('objID', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('objName', models.CharField(max_length=200)),
                ('objRA2000', models.CharField(max_length=200)),
                ('objDec2000', models.CharField(max_length=200)),
                ('objConst', models.CharField(max_length=200)),
                ('objMag', models.CharField(max_length=200)),
                ('objSize', models.CharField(max_length=200)),
                ('objType', models.CharField(max_length=200)),
                ('objClass', models.CharField(max_length=200)),
                ('objCatalogs', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='openNGC',
        ),
        migrations.AddField(
            model_name='imager',
            name='imagerType',
            field=models.CharField(choices=[('CMOS', 'CMOS'), ('CCD', 'CCD')], default='CMOS', max_length=4),
        ),
        migrations.AddField(
            model_name='telescope',
            name='telescopeType',
            field=models.CharField(choices=[('NE', 'Newtonian'), ('SC', 'Schmidt-Cassegrain'), ('CC', 'Classical Cassegrain'), ('RC', 'Ritchey Cretien Cassegrain'), ('MC', 'Mak-Cassegrain'), ('OT', 'Other')], default='NE', max_length=2),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='instType',
            field=models.CharField(choices=[('AS', 'AllSkyCam'), ('WE', 'Weather Station')], default='AS', max_length=2),
        ),
    ]
