# Generated by Django 4.0.10 on 2024-06-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_objectscatalog_delete_openngc_imager_imagertype_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='objectsCatalog',
        ),
        migrations.RenameField(
            model_name='fitsfile',
            old_name='thisUNID',
            new_name='fitsFileId',
        ),
        migrations.RenameField(
            model_name='fitsheader',
            old_name='thisUNID',
            new_name='fitsHeaderId',
        ),
        migrations.RenameField(
            model_name='imager',
            old_name='thisUNID',
            new_name='imagerId',
        ),
        migrations.RenameField(
            model_name='instrument',
            old_name='thisUNID',
            new_name='instrumentId',
        ),
        migrations.RenameField(
            model_name='observatory',
            old_name='thisUNID',
            new_name='observatoryId',
        ),
        migrations.RenameField(
            model_name='observer',
            old_name='thisUNID',
            new_name='observerId',
        ),
        migrations.RenameField(
            model_name='telescope',
            old_name='thisUNID',
            new_name='telescopeId',
        ),
        migrations.AddField(
            model_name='observatory',
            name='elevation',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='latitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='longitude',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
