# Generated by Django 4.0.10 on 2024-06-02 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0007_delete_objectscatalog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitsheader',
            name='parentUNID',
        ),
        migrations.DeleteModel(
            name='fitsFile',
        ),
        migrations.DeleteModel(
            name='fitsHeader',
        ),
    ]
