# Generated by Django 4.0.10 on 2024-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_remove_fitsheader_parentunid_delete_fitsfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observatory',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
        ),
    ]
