# Generated by Django 4.0.10 on 2024-06-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_alter_observatory_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telescope',
            name='telescopeType',
            field=models.CharField(choices=[('NE', 'Newtonian'), ('SC', 'Schmidt-Cassegrain'), ('CC', 'Classical Cassegrain'), ('RC', 'Ritchey Cretien Cassegrain'), ('MC', 'Mak-Cassegrain'), ('RE', 'Refractor'), ('OT', 'Other')], default='NE', max_length=2),
        ),
    ]
