# Generated by Django 4.0.10 on 2024-06-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_remove_imager_instrument_delete_instrument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observer',
            name='middlename',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
