# Generated by Django 4.0.10 on 2024-06-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0012_alter_observer_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observer',
            name='observatory',
        ),
        migrations.RemoveField(
            model_name='telescope',
            name='observatory',
        ),
        migrations.AddField(
            model_name='observatory',
            name='imagerId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.imager'),
        ),
        migrations.AddField(
            model_name='observatory',
            name='telescopeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.telescope'),
        ),
        migrations.AddField(
            model_name='observer',
            name='observatoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
        ),
        migrations.AddField(
            model_name='telescope',
            name='observatoryId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='setup.observatory'),
        ),
    ]
