# Generated by Django 5.1.2 on 2024-10-09 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0013_remove_observer_observatory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observatory',
            name='imagerId',
        ),
        migrations.RemoveField(
            model_name='observatory',
            name='telescopeId',
        ),
    ]
