# Generated by Django 5.1.2 on 2024-10-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_remove_observatory_imagerid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imager',
            name='imagerId',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observatory',
            name='observatoryId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='observer',
            name='observerId',
            field=models.AutoField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='telescope',
            name='telescopeId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
