# Generated by Django 5.1.2 on 2024-10-10 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_currentconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='currentConfig',
        ),
    ]
