# Generated by Django 5.1.2 on 2024-11-06 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_delete_currentconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='observer',
        ),
    ]
