# Generated by Django 5.1.4 on 2024-12-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0020_currentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='imager',
            name='imagerColor',
            field=models.CharField(choices=[('RGB', 'RGB'), ('Mono', 'Mono')], default='RGB', max_length=4),
        ),
    ]
