# Generated by Django 5.1.5 on 2025-01-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_backend', models.CharField(max_length=255)),
                ('email_host', models.CharField(max_length=255)),
                ('email_port', models.IntegerField()),
                ('email_use_tls', models.BooleanField()),
                ('email_host_user', models.CharField(max_length=255)),
                ('email_host_password', models.CharField(max_length=255)),
                ('sender_email', models.CharField(max_length=255)),
                ('recipient_email', models.CharField(max_length=255)),
                ('twilio_sid', models.CharField(max_length=255)),
                ('twilio_token', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppsourcepath', models.CharField(max_length=255)),
                ('pprepopath', models.CharField(max_length=255)),
            ],
        ),
    ]
