# Generated by Django 5.1.5 on 2025-01-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationsconfig',
            name='twilio_sid',
        ),
        migrations.RemoveField(
            model_name='communicationsconfig',
            name='twilio_token',
        ),
    ]
