# Generated by Django 5.1.5 on 2025-01-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_remove_communicationsconfig_twilio_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_host_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_host_user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_use_tls',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='recipient_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='communicationsconfig',
            name='sender_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='pprepopath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='ppsourcepath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
