# Generated by Django 5.1.5 on 2025-01-25 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_alter_communicationsconfig_email_host_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communicationsconfig',
            name='email_backend',
        ),
    ]
