# Generated by Django 5.1.5 on 2025-02-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_remove_communicationsconfig_email_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsconfig',
            name='email_host',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='pprepopath',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='repositoryconfig',
            name='ppsourcepath',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
